# Generated by Django 3.2.8 on 2021-10-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211021_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancer_order', 'Can cancel order')]},
        ),
    ]
